### ISSUE TITLE
I can't delete wrong tag in "Skills"

### ISSUE THREAD

**Issue by sadra** [Atbox/faq#1]
Today I tried to make a resume, but faced with a problem in **Skills** section.
I was writing my skills. It said there was a wrong character in tags. Tried to delete it, but i couldn't. Please check.

**The wrong character alert:**
<img width="818" alt="screen shot 2017-07-25 at 10 48 34" src="https://user-images.githubusercontent.com/18361407/28558618-ede2eef0-7127-11e7-94e4-c2d2b1903429.png">

**After I deteled it:**
<img width="823" alt="screen shot 2017-07-25 at 10 48 27" src="https://user-images.githubusercontent.com/18361407/28558623-f2fa56d0-7127-11e7-9e63-302dda0fe195.png">

**After I pressed the "Continiue", the wrong tag came back again and alert was still there:**
<img width="817" alt="screen shot 2017-07-25 at 10 48 19" src="https://user-images.githubusercontent.com/18361407/28558619-ee3b0e00-7127-11e7-9c8e-ffbcc70cc2ae.png">

**Comment by saadeghi** [comment]
@sadra Thanks for reporting. I'll fix it today ✌️

**Comment by saadeghi** [comment]
@sadra Fixed. Thanks for reporting 👍
